

all: results

results:
	micall analyze sample --denovo --keep_scratch --debug_remap --bad_cycles_csv bad_cycles_239196.csv --project_code V3LOOP -- $(PWD)/63902A-V3-3-V3LOOP_S39_L001_R1_001.fastq.gz $(PWD)/63902A-V3-3-V3LOOP_S39_L001_R2_001.fastq.gz $(PWD)/results/


.PHONY: all
.SECONDARY:
