

all: results

results:
	micall analyze sample --denovo --keep_scratch --debug_remap --bad_cycles_csv 63902A-V3-3-V3LOOP_S39_L001_R1_001.fastq.gz 63902A-V3-3-V3LOOP_S39_L001_R2_001.fastq.gz --project_code V3LOOP -- 63902A-V3-3-V3LOOP_S39_L001_R1_001.fastq.gz 63902A-V3-3-V3LOOP_S39_L001_R2_001.fastq.gz ./results/


.PHONY: all
.SECONDARY:
